//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterClassCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
        public decimal cost { get; set; }
        public int client_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public int status_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
    }
}
